# Generated by Django 4.2.3 on 2023-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
