# Generated by Django 4.2.3 on 2023-07-18 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinks.categories'),
        ),
    ]
